name: 'release-changelog'
on:
  push:
    tags:
      'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Build Changelog
        id: changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: /CHANGELOG.md
      - name: Show changelog
        run: |
          echo ${{ steps.changelog.outputs.changelog }}

